### ISSUE TITLE
Even/Odd row background

### ISSUE THREAD

**Issue by mbilbille** [oldergod/red#22]
Below are colors used on website:

``` css
.match-row--odd {
    background-color: $gray-lighter;
}
.match-row--even {
    background-color:$white;
}
```

| Mobile | Web |
| --- | --- |
| ![Android](https://drive.google.com/uc?export=view&id=0B8E1V5-VDcUdQ0dsR3E2NlRYZzg) | ![Web](https://drive.google.com/uc?export=view&id=0B8E1V5-VDcUdN3FEOWxwS0RId2c) |
